# Generated by Django 4.2.16 on 2026-04-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_seed_predefined_categories'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tracker_tra_user_id_177eba_idx',
            old_name='tracker_tra_user_id_type_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tracker_tra_user_id_d71426_idx',
            old_name='tracker_tra_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tracker_tra_user_id_ea3525_idx',
            old_name='tracker_tra_user_id_cat_idx',
        ),
    ]
